t=turtle.Pen()
>>> t.colour(0,0,1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Turtle' object has no attribute 'colour'
#use american spelling of colour
>>> t.color(0,0,1)
#RGB
>>> t.begin_fill()
>>> t.forward(160)
>>> t.left(90)
>>> t.forward(40)
>>> t.left(90)
>>> t.forward(40)
>>> t.right(90)
>>> t.forward(40)
>>> t.left(90)
>>> t.forward(80)
>>> t.left(90)
>>> t.forward(40)
>>> t.left(90)
>>> t.left(180)
>>> t.forward(40)
>>> t.left(90)
>>> t.forward(40)
>>> t.end_fill()
>>> t.up()
>>> t.color(0,0,0)
>>> t.left(90)
>>> t.forward(40)
>>> t.right(90)
>>> t.forward(20)
>>> t.left(180)
>>> t.forward(20)
>>> t.left(180)
>>> t.left(90)
>>> t.left(180)
>>> t.circle(15)
>>> t.down()
>>> t.circle(15)
>>> t.begin_fill()
>>> t.circle(15)
>>> t.end_fill()
>>> t.up()
>>> t.left(180)
>>> t.forward(80)
>>> t.left(180)
>>> t.down()
>>> t.circle(15)
>>> t.begin_fill()
>>> t.circle(15)
>>> t.end_fill()
>>> 
